export interface Example {
  keywords: string[];
  feature: string;
  advantage: string;
  benefit: string;
  emotion: string;
  copy: string;
}

export const examples: Example[] = [
  // ========== CAMPINGS (20 voorbeelden) ==========
  {
    keywords: ["réservation", "booking", "reservation", "réserver", "disponibilité", "calendrier"],
    feature: "Réservation en ligne 24/7",
    advantage: "Réduit les appels téléphoniques de 70%",
    benefit: "Augmente vos réservations même la nuit",
    emotion: "Tranquillité & Revenus automatiques",
    copy: "Vos clients réservent pendant que vous dormez.",
  },
  {
    keywords: ["wifi", "internet", "connexion", "réseau", "4g", "5g"],
    feature: "WiFi haut débit sur tout le camping",
    advantage: "Satisfaction client garantie",
    benefit: "Augmentation des avis 5 étoiles de 40%",
    emotion: "Fierté & Réputation",
    copy: "Le WiFi qui transforme vos clients en ambassadeurs.",
  },
  {
    keywords: ["emplacement", "place", "pitch", "parcelle", "tente", "caravane", "camping-car"],
    feature: "Gestion intelligente des emplacements",
    advantage: "Optimisation automatique de l'occupation",
    benefit: "Augmente votre taux d'occupation de 25%",
    emotion: "Efficacité & Rentabilité maximale",
    copy: "Chaque m² génère plus de revenus, automatiquement.",
  },
  {
    keywords: ["animation", "activité", "événement", "programme", "kids", "enfants"],
    feature: "Programme d'animations personnalisé",
    advantage: "Fidélisation des familles",
    benefit: "Taux de retour client multiplié par 3",
    emotion: "Joie & Mémoires inoubliables",
    copy: "Créez des souvenirs qui ramènent vos clients chaque été.",
  },
  {
    keywords: ["piscine", "swimming", "bain", "aquatique", "bassin", "aquatique"],
    feature: "Piscine chauffée avec espace aquatique",
    advantage: "Différenciation concurrentielle",
    benefit: "Justification d'un prix premium de 30%",
    emotion: "Plaisir & Expérience premium",
    copy: "La piscine qui justifie votre tarif haut de gamme.",
  },
  {
    keywords: ["sanitaire", "douche", "toilette", "bloc", "hygiène", "wc", "lavabo"],
    feature: "Blocs sanitaires modernes et propres",
    advantage: "Critère #1 de choix des campeurs",
    benefit: "Réduction des réclamations de 80%",
    emotion: "Confort & Confiance",
    copy: "Des sanitaires qui parlent mieux que vos photos.",
  },
  {
    keywords: ["mobil-home", "chalet", "location", "hébergement", "gîte", "cabane"],
    feature: "Location de mobil-homes et chalets",
    advantage: "Revenus complémentaires garantis",
    benefit: "Augmentation du CA de 35% hors saison",
    emotion: "Diversification & Sécurité financière",
    copy: "Des hébergements qui génèrent des revenus toute l'année.",
  },
  {
    keywords: ["restaurant", "bar", "snack", "repas", "cuisine", "cantine"],
    feature: "Restaurant et bar sur place",
    advantage: "Confort client sans sortir du camping",
    benefit: "Augmentation du panier moyen de 50%",
    emotion: "Convenance & Expérience complète",
    copy: "Le restaurant qui transforme un séjour en expérience totale.",
  },
  {
    keywords: ["épicerie", "supermarché", "shop", "boutique", "commerce"],
    feature: "Épicerie et boutique sur place",
    advantage: "Service client complet",
    benefit: "Revenus supplémentaires de 20%",
    emotion: "Pratique & Service tout-en-un",
    copy: "L'épicerie qui transforme chaque client en revenu supplémentaire.",
  },
  {
    keywords: ["laverie", "lavage", "machine", "linge", "lessive"],
    feature: "Laverie moderne et équipée",
    advantage: "Service essentiel pour séjours longs",
    benefit: "Fidélisation client +30%",
    emotion: "Pratique & Confort prolongé",
    copy: "La laverie qui prolonge les séjours de vos clients.",
  },
  {
    keywords: ["terrain", "sport", "football", "basket", "volley", "jeux"],
    feature: "Terrains de sport et aires de jeux",
    advantage: "Attraction pour familles et groupes",
    benefit: "Augmentation réservations groupes de 45%",
    emotion: "Dynamisme & Convivialité",
    copy: "Les terrains qui transforment votre camping en destination.",
  },
  {
    keywords: ["chien", "animal", "pets", "animaux", "accepté", "compagnon"],
    feature: "Camping acceptant les animaux",
    advantage: "Marché de niche captif",
    benefit: "Augmentation réservations de 25%",
    emotion: "Inclusion & Famille complète",
    copy: "L'accueil des animaux qui ouvre un marché de 40% de campeurs.",
  },
  {
    keywords: ["électricité", "borne", "recharge", "électrique", "voiture"],
    feature: "Bornes de recharge électrique",
    advantage: "Service moderne et différenciant",
    benefit: "Attraction clientèle premium +20%",
    emotion: "Modernité & Responsabilité",
    copy: "Les bornes qui positionnent votre camping comme innovant.",
  },
  {
    keywords: ["sécurité", "surveillance", "gardien", "contrôle", "accès"],
    feature: "Sécurité 24/7 avec gardiennage",
    advantage: "Rassurance client essentielle",
    benefit: "Réduction réclamations de 60%",
    emotion: "Sécurité & Tranquillité",
    copy: "La sécurité qui rassure et justifie votre prix.",
  },
  {
    keywords: ["nature", "écologie", "bio", "durable", "vert", "environnement"],
    feature: "Camping écologique et durable",
    advantage: "Positionnement premium et responsable",
    benefit: "Justification prix +25%",
    emotion: "Responsabilité & Fierté",
    copy: "L'écologie qui transforme votre camping en choix conscient.",
  },
  {
    keywords: ["plage", "mer", "lac", "eau", "bord", "rivage"],
    feature: "Accès direct à la plage/lac",
    advantage: "Avantage concurrentiel majeur",
    benefit: "Taux d'occupation +40%",
    emotion: "Privilège & Exclusivité",
    copy: "L'accès direct qui justifie votre premium.",
  },
  {
    keywords: ["vélo", "location", "bike", "cyclisme", "piste"],
    feature: "Location de vélos sur place",
    advantage: "Service complémentaire pratique",
    benefit: "Revenus supplémentaires +15%",
    emotion: "Mobilité & Découverte",
    copy: "Les vélos qui enrichissent l'expérience client.",
  },
  {
    keywords: ["réception", "accueil", "conciergerie", "service", "client"],
    feature: "Réception accueillante et professionnelle",
    advantage: "Première impression décisive",
    benefit: "Satisfaction client +50%",
    emotion: "Hospitalité & Professionnalisme",
    copy: "L'accueil qui transforme un client en ambassadeur.",
  },
  {
    keywords: ["météo", "climat", "abri", "couvert", "intérieur"],
    feature: "Espaces couverts en cas de mauvais temps",
    advantage: "Confort par tous les temps",
    benefit: "Réduction annulations de 30%",
    emotion: "Préparation & Sérénité",
    copy: "Les espaces couverts qui garantissent le confort.",
  },
  {
    keywords: ["groupe", "séminaire", "entreprise", "team", "événement"],
    feature: "Espaces dédiés aux groupes",
    advantage: "Revenus prévisibles et garantis",
    benefit: "CA groupes +50%",
    emotion: "Organisation & Succès",
    copy: "Les espaces groupes qui transforment votre camping en destination corporate.",
  },
  
  // ========== HOTELS (20 voorbeelden) ==========
  {
    keywords: ["check-in", "enregistrement", "arrivée", "réception", "accueil"],
    feature: "Check-in express en 2 minutes",
    advantage: "Fini les files d'attente",
    benefit: "Satisfaction client +35% dès l'arrivée",
    emotion: "Efficacité & Première impression parfaite",
    copy: "La première impression qui vaut 5 étoiles.",
  },
  {
    keywords: ["petit-déjeuner", "breakfast", "buffet", "matin", "repas"],
    feature: "Petit-déjeuner buffet local et bio",
    advantage: "Expérience mémorable dès le matin",
    benefit: "Augmente les avis positifs de 50%",
    emotion: "Délicatesse & Authenticité",
    copy: "Le petit-déjeuner qui transforme un séjour en expérience.",
  },
  {
    keywords: ["spa", "wellness", "relaxation", "massage", "bien-être", "hammam", "sauna"],
    feature: "Espace spa et bien-être",
    advantage: "Justification d'un prix premium",
    benefit: "Augmentation du panier moyen de 45%",
    emotion: "Détente & Luxe accessible",
    copy: "Le spa qui transforme une nuit en évasion.",
  },
  {
    keywords: ["parking", "voiture", "garage", "stationnement", "voiturier"],
    feature: "Parking sécurisé gratuit",
    advantage: "Critère décisif pour 60% des clients",
    benefit: "Réduction des annulations de dernière minute",
    emotion: "Sécurité & Sérénité",
    copy: "Le parking qui rassure avant même l'arrivée.",
  },
  {
    keywords: ["loyalty", "fidélité", "programme", "points", "récompense", "membre"],
    feature: "Programme de fidélité avec récompenses",
    advantage: "Rétention client automatique",
    benefit: "Taux de retour client multiplié par 4",
    emotion: "Reconnaissance & Appartenance",
    copy: "Transformez vos clients en ambassadeurs fidèles.",
  },
  {
    keywords: ["chambre", "suite", "room", "appartement", "hébergement"],
    feature: "Chambres design et confortables",
    advantage: "Expérience client mémorable",
    benefit: "Taux de recommandation +60%",
    emotion: "Confort & Raffinement",
    copy: "Les chambres qui transforment une nuit en souvenir.",
  },
  {
    keywords: ["room-service", "service", "chambre", "commande", "livraison"],
    feature: "Room service 24/7",
    advantage: "Confort et convenance maximale",
    benefit: "Augmentation panier moyen de 30%",
    emotion: "Luxe & Service personnalisé",
    copy: "Le room service qui transforme votre hôtel en refuge.",
  },
  {
    keywords: ["restaurant", "gastronomie", "cuisine", "chef", "menu"],
    feature: "Restaurant gastronomique sur place",
    advantage: "Expérience culinaire complète",
    benefit: "Augmentation séjours de 40%",
    emotion: "Découverte & Excellence",
    copy: "Le restaurant qui transforme votre hôtel en destination.",
  },
  {
    keywords: ["bar", "cocktail", "apéritif", "happy-hour", "boisson"],
    feature: "Bar lounge avec cocktails signature",
    advantage: "Expérience sociale et conviviale",
    benefit: "Revenus F&B +35%",
    emotion: "Convivialité & Sophistication",
    copy: "Le bar qui transforme votre hôtel en lieu de rencontre.",
  },
  {
    keywords: ["salle", "réunion", "séminaire", "conférence", "événement"],
    feature: "Salles de réunion et séminaires",
    advantage: "Marché corporate captif",
    benefit: "Revenus groupes +50%",
    emotion: "Professionnalisme & Organisation",
    copy: "Les salles qui transforment votre hôtel en hub corporate.",
  },
  {
    keywords: ["fitness", "gym", "sport", "entraînement", "salle"],
    feature: "Salle de fitness moderne",
    advantage: "Service essentiel pour voyageurs d'affaires",
    benefit: "Fidélisation client +25%",
    emotion: "Bien-être & Équilibre",
    copy: "Le fitness qui transforme votre hôtel en choix santé.",
  },
  {
    keywords: ["business", "centre", "bureau", "travail", "wifi"],
    feature: "Business center équipé",
    advantage: "Service essentiel voyageurs pro",
    benefit: "Taux d'occupation semaine +30%",
    emotion: "Productivité & Efficacité",
    copy: "Le business center qui transforme votre hôtel en bureau.",
  },
  {
    keywords: ["conciergerie", "concierge", "service", "assistance", "aide"],
    feature: "Conciergerie personnalisée",
    advantage: "Service premium différenciant",
    benefit: "Satisfaction client +45%",
    emotion: "Excellence & Attention",
    copy: "La conciergerie qui transforme un séjour en expérience sur mesure.",
  },
  {
    keywords: ["terrasse", "balcon", "vue", "panorama", "extérieur"],
    feature: "Chambres avec terrasse et vue",
    advantage: "Expérience premium mémorable",
    benefit: "Justification prix +40%",
    emotion: "Évasion & Privilège",
    copy: "Les terrasses qui transforment votre hôtel en évasion.",
  },
  {
    keywords: ["familial", "enfant", "kids", "famille", "jeux"],
    feature: "Services et équipements familiaux",
    advantage: "Marché famille captif",
    benefit: "Réservations familles +55%",
    emotion: "Accueil & Confort familial",
    copy: "Les services famille qui transforment votre hôtel en destination.",
  },
  {
    keywords: ["accessibilité", "handicap", "pmr", "mobilité", "réduite"],
    feature: "Accessibilité PMR complète",
    advantage: "Marché de niche captif",
    benefit: "Réservations accessibilité +35%",
    emotion: "Inclusion & Égalité",
    copy: "L'accessibilité qui ouvre votre hôtel à tous.",
  },
  {
    keywords: ["mariage", "cérémonie", "événement", "réception", "wedding"],
    feature: "Espaces dédiés aux mariages",
    advantage: "Revenus événements premium",
    benefit: "CA événements +60%",
    emotion: "Célébration & Mémoires",
    copy: "Les espaces mariage qui transforment votre hôtel en destination rêvée.",
  },
  {
    keywords: ["sécurité", "sûreté", "surveillance", "contrôle", "accès"],
    feature: "Sécurité 24/7 et contrôle d'accès",
    advantage: "Rassurance client essentielle",
    benefit: "Réduction réclamations de 50%",
    emotion: "Sécurité & Tranquillité",
    copy: "La sécurité qui rassure et justifie votre prix.",
  },
  {
    keywords: ["écologie", "durable", "bio", "vert", "environnement", "green"],
    feature: "Hôtel écologique et durable",
    advantage: "Positionnement premium responsable",
    benefit: "Justification prix +30%",
    emotion: "Responsabilité & Fierté",
    copy: "L'écologie qui transforme votre hôtel en choix conscient.",
  },
  {
    keywords: ["local", "régional", "artisan", "produit", "terroir"],
    feature: "Produits locaux et régionaux",
    advantage: "Authenticité et différenciation",
    benefit: "Satisfaction client +40%",
    emotion: "Authenticité & Découverte",
    copy: "Les produits locaux qui transforment votre hôtel en expérience authentique.",
  },
  
  // ========== OUTDOOR ACTIVITÉS (20 voorbeelden) ==========
  {
    keywords: ["activité", "sport", "aventure", "randonnée", "kayak", "vélo", "escalade"],
    feature: "Réservation d'activités en ligne",
    advantage: "Planification simplifiée pour vos clients",
    benefit: "Augmentation des réservations d'activités de 60%",
    emotion: "Anticipation & Excitement",
    copy: "Vos clients s'enthousiasment avant même d'arriver.",
  },
  {
    keywords: ["matériel", "équipement", "location", "prêt", "fourniture"],
    feature: "Location de matériel professionnel inclus",
    advantage: "Barrière à l'entrée supprimée",
    benefit: "Conversion visiteurs → clients +50%",
    emotion: "Accessibilité & Facilité",
    copy: "Le matériel qui transforme 'je voudrais' en 'je réserve'.",
  },
  {
    keywords: ["guide", "accompagnateur", "moniteur", "expert", "instructeur"],
    feature: "Guides locaux certifiés et passionnés",
    advantage: "Sécurité et découverte garanties",
    benefit: "Taux de satisfaction de 98%",
    emotion: "Confiance & Découverte authentique",
    copy: "Des guides qui transforment une activité en aventure mémorable.",
  },
  {
    keywords: ["photo", "vidéo", "souvenir", "mémorial", "capture", "gopro"],
    feature: "Photos et vidéos professionnelles incluses",
    advantage: "Souvenirs partagés = publicité gratuite",
    benefit: "Augmentation du bouche-à-oreille de 200%",
    emotion: "Mémoire & Partage",
    copy: "Vos clients deviennent vos meilleurs influenceurs.",
  },
  {
    keywords: ["groupe", "team", "entreprise", "séminaire", "événement", "team-building"],
    feature: "Packages groupes sur mesure",
    advantage: "Revenus prévisibles et garantis",
    benefit: "Augmentation du chiffre d'affaires de 40%",
    emotion: "Organisation & Succès d'équipe",
    copy: "Transformez les groupes en clients récurrents.",
  },
  {
    keywords: ["annulation", "flexible", "remboursement", "modification", "annuler"],
    feature: "Annulation flexible jusqu'à 24h avant",
    advantage: "Réduction de l'anxiété d'achat",
    benefit: "Augmentation des réservations de 35%",
    emotion: "Sérénité & Confiance",
    copy: "La flexibilité qui rassure et convertit.",
  },
  {
    keywords: ["kayak", "canoë", "rafting", "eau", "rivière", "paddle"],
    feature: "Activités nautiques encadrées",
    advantage: "Expérience unique et sécurisée",
    benefit: "Réservations nautiques +70%",
    emotion: "Aventure & Sécurité",
    copy: "Les activités nautiques qui transforment une journée en aventure.",
  },
  {
    keywords: ["escalade", "via", "ferrata", "grimpe", "rocher", "falaise"],
    feature: "Escalade et via ferrata sécurisées",
    advantage: "Expérience intense et mémorable",
    benefit: "Réservations escalade +65%",
    emotion: "Défi & Accomplissement",
    copy: "L'escalade qui transforme vos clients en héros.",
  },
  {
    keywords: ["randonnée", "trek", "rando", "sentier", "balade", "montagne"],
    feature: "Randonnées guidées en montagne",
    advantage: "Découverte sécurisée de la nature",
    benefit: "Réservations randonnées +55%",
    emotion: "Découverte & Connexion nature",
    copy: "Les randonnées qui transforment une promenade en expérience.",
  },
  {
    keywords: ["vélo", "vtt", "mountain", "bike", "cyclisme", "piste"],
    feature: "Sorties VTT et vélo de route",
    advantage: "Activité accessible et populaire",
    benefit: "Réservations vélo +50%",
    emotion: "Liberté & Performance",
    copy: "Le vélo qui transforme vos clients en explorateurs.",
  },
  {
    keywords: ["parapente", "parachute", "vol", "ciel", "aérien"],
    feature: "Parapente et activités aériennes",
    advantage: "Expérience unique et intense",
    benefit: "Réservations aériennes +80%",
    emotion: "Liberté & Sensation",
    copy: "Le parapente qui transforme une activité en moment inoubliable.",
  },
  {
    keywords: ["canyoning", "canyon", "descente", "cascade", "eau"],
    feature: "Canyoning encadré et sécurisé",
    advantage: "Expérience aventure unique",
    benefit: "Réservations canyoning +75%",
    emotion: "Aventure & Défi",
    copy: "Le canyoning qui transforme vos clients en aventuriers.",
  },
  {
    keywords: ["spéléologie", "grotte", "caverne", "souterrain"],
    feature: "Spéléologie guidée en sécurité",
    advantage: "Découverte souterraine unique",
    benefit: "Réservations spéléo +60%",
    emotion: "Exploration & Découverte",
    copy: "La spéléologie qui transforme une sortie en expédition.",
  },
  {
    keywords: ["sécurité", "sûreté", "encadrement", "moniteur", "certifié"],
    feature: "Encadrement par moniteurs certifiés",
    advantage: "Sécurité maximale garantie",
    benefit: "Taux de satisfaction de 99%",
    emotion: "Confiance & Sérénité",
    copy: "L'encadrement qui rassure et transforme l'anxiété en confiance.",
  },
  {
    keywords: ["débutant", "initiation", "niveau", "facile", "accessible"],
    feature: "Activités adaptées aux débutants",
    advantage: "Accessibilité maximale",
    benefit: "Conversion débutants +80%",
    emotion: "Accessibilité & Découverte",
    copy: "Les activités débutants qui transforment 'je ne peux pas' en 'je l'ai fait'.",
  },
  {
    keywords: ["expérience", "pack", "journée", "complet", "forfait"],
    feature: "Forfaits expérience journée complète",
    advantage: "Valeur perçue maximale",
    benefit: "Panier moyen +60%",
    emotion: "Valeur & Expérience complète",
    copy: "Les forfaits qui transforment une activité en journée mémorable.",
  },
  {
    keywords: ["saison", "hiver", "été", "printemps", "automne"],
    feature: "Activités adaptées à toutes les saisons",
    advantage: "Revenus toute l'année",
    benefit: "CA annuel +45%",
    emotion: "Continuité & Diversité",
    copy: "Les activités saisonnières qui transforment votre activité en business annuel.",
  },
  {
    keywords: ["local", "régional", "terroir", "authentique", "culture"],
    feature: "Découverte du terroir et culture locale",
    advantage: "Expérience authentique différenciante",
    benefit: "Satisfaction client +50%",
    emotion: "Authenticité & Enrichissement",
    copy: "La découverte locale qui transforme une activité en expérience culturelle.",
  },
  {
    keywords: ["famille", "enfant", "kids", "parent", "génération"],
    feature: "Activités adaptées aux familles",
    advantage: "Marché famille captif",
    benefit: "Réservations familles +65%",
    emotion: "Partage & Mémoires familiales",
    copy: "Les activités famille qui transforment une sortie en souvenir partagé.",
  },
  {
    keywords: ["écologie", "durable", "nature", "environnement", "respect"],
    feature: "Activités respectueuses de l'environnement",
    advantage: "Positionnement responsable",
    benefit: "Attraction clientèle consciente +40%",
    emotion: "Responsabilité & Fierté",
    copy: "L'écologie qui transforme votre activité en choix conscient.",
  },
  
  // GÉNÉRIQUE (pour fallback)
  {
    keywords: ["update", "mise à jour", "statut"],
    feature: "Mises à jour automatiques",
    advantage: "Moins d'appels téléphoniques",
    benefit: "Gagnez 3h de temps libre / semaine",
    emotion: "Sérénité & Contrôle total",
    copy: "Des mises à jour en temps réel sans passer un seul appel.",
  },
  {
    keywords: ["dashboard", "tableau", "bord"],
    feature: "Tableau de bord centralisé",
    advantage: "Tout le suivi à un seul endroit",
    benefit: "Réduction drastique des erreurs",
    emotion: "Confiance & Professionnalisme",
    copy: "Une source unique de vérité pour zéro erreur.",
  },
];

export function findExampleByKeyword(input: string): Example | null {
  const lowerInput = input.toLowerCase().trim();
  
  for (const example of examples) {
    for (const keyword of example.keywords) {
      if (lowerInput.includes(keyword.toLowerCase())) {
        return example;
      }
    }
  }
  
  return null;
}

export function getRandomExample(): Example {
  return examples[Math.floor(Math.random() * examples.length)];
}

